'use client'

import { useState } from 'react'
import { CloudDownloadIcon } from '@heroicons/react/outline'

import Button from '../../components/Button'
import LoadingSpinner from '../../components/LoadingSpinner'
import { fetchCsv, filterCsv, downloadCsv } from '../../helpers/export'
import { searchRequest, queryOrFiltersAreSet, CtSearchRequestBody } from './search'

// Static CSV served from /export/clinical-trials (generated by the pipeline).
const FULL_DATA_PATH = 'clinical-trials/pandemic-pact-clinical-trials.csv'
const FILTERED_DATA_FILENAME = 'pandemic-pact-filtered-clinical-trials.csv'

const iconClasses = 'w-5 h-5'

export function DownloadFullDataButton() {
    const [exporting, setExporting] = useState(false)

    const exportCsv = () => {
        if (exporting) return
        setExporting(true)

        fetchCsv(FULL_DATA_PATH)
            .then(csv => {
                downloadCsv(csv, 'pandemic-pact-clinical-trials.csv')
                setExporting(false)
            })
            .catch(error => {
                console.error(error)
                setExporting(false)
            })
    }

    return (
        <Button
            disabled={exporting}
            onClick={exportCsv}
            colour="grey"
            size="xsmall"
            customClasses="flex items-center justify-center self-start gap-2"
        >
            <span>Download Full Data</span>
            {exporting ? (
                <LoadingSpinner className={`${iconClasses} animate-spin shrink-0`} />
            ) : (
                <CloudDownloadIcon className={iconClasses} />
            )}
        </Button>
    )
}

export function DownloadFilteredDataButton({
    searchRequestBody,
}: {
    searchRequestBody: CtSearchRequestBody
}) {
    const [exporting, setExporting] = useState(false)

    const exportCsv = () => {
        if (exporting) return
        setExporting(true)

        Promise.all([
            fetchCsv(FULL_DATA_PATH),
            queryOrFiltersAreSet(searchRequestBody)
                ? searchRequest('export', searchRequestBody)
                : Promise.resolve(null),
        ])
            .then(([csv, searchResponse]) => {
                let filteredCsv = csv

                if (searchResponse !== null) {
                    filteredCsv = filterCsv(filteredCsv, searchResponse.trialIDs)
                }

                downloadCsv(filteredCsv, FILTERED_DATA_FILENAME)
                setExporting(false)
            })
            .catch(error => {
                console.error(error)
                setExporting(false)
            })
    }

    return (
        <Button
            disabled={exporting}
            onClick={exportCsv}
            colour="grey"
            size="xsmall"
            customClasses="flex items-center justify-center self-start gap-2"
        >
            <span>Download Filtered Data</span>
            {exporting ? (
                <LoadingSpinner className={`${iconClasses} animate-spin shrink-0`} />
            ) : (
                <CloudDownloadIcon className={iconClasses} />
            )}
        </Button>
    )
}
